apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: default
  labels:
    app: backend
spec:
  type: LoadBalancer
  ports:
    - port: 5000
      targetPort: 5000
      name: http
  selector:
    app: backend